# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "Markdown"

on:  # yamllint disable-line rule:truthy
    pull_request:
        paths:
        - "**/*.md"
        - ".markdownlint-cli2.yaml"
    push:
        branches:
        - "master"
        paths:
        - "**/*.md"
        - ".markdownlint-cli2.yaml"
# Add [skip ci] to commit message to skip CI.

permissions:
    contents: "read"

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    markdown:
        name: "Markdown"
        runs-on: "ubuntu-22.04"
        timeout-minutes: 1
        steps:
        -
            name: "Checkout repository"
            uses: "actions/checkout@v3"
        -
            name: "Check Markdown documents"
            uses: "DavidAnson/markdownlint-cli2-action@v9"
            with:
                globs: "**/*.md"

    links:
        name: "Links"
        runs-on: "ubuntu-22.04"
        timeout-minutes: 10
        steps:
        -
            name: "Checkout repository"
            uses: "actions/checkout@v4"
        -
            name: "Run Lychee"
            uses: "lycheeverse/lychee-action@v1.8.0"
            with:
                args: "--verbose --no-progress --require-https './**/*.md'"
                output: "${{ runner.temp }}/lychee/out.md"
                fail: true
